php_version = "8.3.0"

[source]
paths = ["packages/laravel"]
includes = ["vendor"]
excludes = ["./vendor/composer", "./vendor/symfony", "packages/laravel/vendor"]

[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
space_after_logical_not_unary_prefix_operator = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
array_table_style_alignment = false
