<?php

namespace Hybridly\Actions;

use Hybridly\Configuration\Configuration;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Support\Facades\File;
use RuntimeException;

final readonly class GenerateRoutesDefinitionsAction
{
    public const ROUTES_PATH = '.hybridly/routes.d.ts';
    private const BINDING_PLACEHOLDER = '__key_placeholder__';

    public function __construct(
        private Application $application,
    ) {}

    public function __invoke(Configuration $config): void
    {
        $route_extractor = $this->application->make($config->router->routesExtractor);
        $definitions = $this->makeDefinitions($route_extractor->toArray());

        File::ensureDirectoryExists(base_path('.hybridly'));

        if (File::put(base_path(self::ROUTES_PATH), $definitions) !== false) {
            return;
        }

        throw new RuntimeException('Could not write route definitions.');
    }

    private function makeDefinitions(array $routing): string
    {
        $definitions = <<<'TS'
        /* eslint-disable */
        /* prettier-ignore */
        // This file has been automatically generated by Hybridly
        // Modifications will be discarded

        declare module 'hybridly' {
            export interface GlobalRouteCollection {
                url: '__URL__'
                routes: __ROUTES__
            }
        }


        export {}
        TS;

        return str_replace(
            [
                '__URL__',
                '__ROUTES__',
                '"' . self::BINDING_PLACEHOLDER . '"',
            ],
            [
                $routing['url'] ?? '',
                json_encode($this->makeRoutes($routing), \JSON_UNESCAPED_SLASHES),
                'any',
            ],
            $definitions,
        );
    }

    private function makeRoutes(array $routing): array
    {
        $routes = [];

        foreach ($routing['routes'] ?? [] as $name => $route) {
            $bindings = [];

            foreach (array_keys($route['bindings'] ?? []) as $key) {
                $bindings[$key] = self::BINDING_PLACEHOLDER;
            }

            $routes[$name] = [
                ...($route['uri'] ?? null ? ['uri' => $route['uri']] : []),
                ...($route['domain'] ?? null ? ['domain' => $route['domain']] : []),
                'wheres' => $route['wheres'] ?? [],
                'bindings' => $bindings,
            ];
        }

        return $routes;
    }
}
