<?php

namespace App\KitchenSink\Navigation\Response;

use App\KitchenSink\Navigation\PreserveState\PreserveStateController;
use Carbon\CarbonImmutable;
use Discovery\Routing\Get;
use Discovery\Routing\Post;
use Discovery\Routing\Prefix;
use Discovery\Routing\Put;
use Discovery\Routing\Web;
use Hybridly\Hybridly;
use Hybridly\HybridResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

use function Hybridly\properties;
use function Hybridly\to_external_url;
use function Hybridly\view;

#[Web, Prefix(uri: '/kitchen-sink/navigation/response', name: 'kitchen-sink.navigation.response')]
final class ResponsesController
{
    #[Get('/', name: 'index')]
    public function __invoke(): HybridResponse
    {
        return view('kitchen-sink::navigation.response.index', [
            'time' => CarbonImmutable::now(),
            'propertiesUpdateCount' => 0,
            'propertiesUpdateMethod' => null,
            'propertiesUpdatedAt' => null,
        ]);
    }

    #[Get('/version-changed', name: 'version-changed')]
    public function versionChanged(Hybridly $hybridly): RedirectResponse
    {
        $hybridly->resolveVersionUsing(fn () => CarbonImmutable::now()->toTimeString());

        return to_action(self::class);
    }

    #[Post('/redirect-back', name: 'redirect-back')]
    public function redirectBack(): RedirectResponse
    {
        return back();
    }

    #[Post('/redirect-external', name: 'redirect-external')]
    public function redirectExternal(): Response
    {
        return to_external_url('https://hybridly.dev');
    }

    #[Post('/redirect-internal', name: 'redirect-internal')]
    public function redirectInternal(): RedirectResponse
    {
        return to_action(PreserveStateController::class);
    }

    #[Post('/download', name: 'download')]
    public function download(): StreamedResponse
    {
        $generated_at = CarbonImmutable::now()->toIso8601String();

        return response()->streamDownload(
            callback: function () use ($generated_at): void {
                echo "This file was generated by the Hybridly kitchen sink.\n";
                echo "Generated at: {$generated_at}\n";
            },
            name: 'hybridly-response-demo.txt',
            headers: [
                'Content-Type' => 'text/plain; charset=UTF-8',
            ],
        );
    }

    #[Post('/properties', name: 'properties.post')]
    #[Put('/properties', name: 'properties.put')]
    public function updateProperties(Request $request): HybridResponse
    {
        $properties_update_count = $request->integer('properties_update_count', default: 0) + 1;

        return properties([
            'propertiesUpdateCount' => $properties_update_count,
            'propertiesUpdateMethod' => strtoupper($request->method()),
            'propertiesUpdatedAt' => CarbonImmutable::now()->toIso8601String(),
        ]);
    }
}
