import type { DynamicConfiguration } from '@hybridly/core'
import fs from 'node:fs'
import path from 'node:path'
import type { ViteOptions } from '../types'

const COMPILER_OPTIONS = {
	target: 'esnext',
	module: 'esnext',
	moduleResolution: 'bundler',
	strict: true,
	skipLibCheck: true,
	sourceMap: true,
	resolveJsonModule: true,
	esModuleInterop: true,
	rootDir: '../',
	noImplicitThis: true,
	noUncheckedIndexedAccess: true,
	allowSyntheticDefaultImports: true,
}

export function generateAppTsConfig(options: ViteOptions, config: DynamicConfiguration) {
	const tsconfig = {
		compilerOptions: {
			...COMPILER_OPTIONS,
			jsx: 'preserve',
			lib: [
				'esnext',
				'dom',
				'dom.iterable',
			],
			types: [
				'vite/client',
				'hybridly/client',
				...(options.tsconfig?.types ?? []),
			],
			paths: {
				'#/*': [
					'./*',
				],
				'~/*': [
					'../*',
				],
				'@/*': [
					`../${config.architecture.root_directory}/*`,
				],
			},
		},
		include: [
			'./*.d.ts',
			...config.architecture.namespaces.flatMap((directory) => `../${directory}`),
			...config.components.views.map(({ path }) => `../${path}`),
			...config.components.layouts.map(({ path }) => `../${path}`),
			...(options.tsconfig?.include ?? []),
		],
		exclude: [
			'../public/**/*',
			...(options.tsconfig?.exclude ?? []),
		],
	}

	write(JSON.stringify(tsconfig, null, 2), 'tsconfig.json')
}

export function generateNodeTsConfig(options: ViteOptions, config: DynamicConfiguration) {
	const tsconfig = {
		compilerOptions: COMPILER_OPTIONS,
		include: [
			'../*.config.ts',
		],
	}

	write(JSON.stringify(tsconfig, null, 2), 'tsconfig.node.json')
}

export function generateLaravelIdeaHelper(config: DynamicConfiguration) {
	const ideJson = {
		$schema: 'https://laravel-ide.com/schema/laravel-ide-v2.json',
		completions: [
			{
				complete: 'staticStrings',
				options: {
					strings: config.components.views.map(({ identifier }) => identifier),
				},
				condition: [
					{
						functionNames: ['hybridly'],
						parameters: [1],
					},
				],
			},
			{
				complete: 'routeName',
				condition: [
					{
						classFqn: ['Hybridly\\Hybridly'],
						methodNames: ['base'],
						parameters: [1],
					},
				],
			},
		],
	}

	write(JSON.stringify(ideJson, null, 2), 'ide.json')
}

export async function generateVueExtensionFile() {
	const file = `
/* eslint-disable */
/* prettier-ignore */
// This file has been automatically generated by Hybridly
// Modifications will be discarded

import 'vue'
import type { Component, VNode, h } from 'vue'

declare module 'vue' {
	interface ComponentCustomOptions {
		properties?: Record<string, any>
		layout?: Component | Component[] | ((r: typeof h, view: VNode, dialog: VNode, properties: Record<string, any>) => VNode | VNode[])
	}
}
`

	write(file, 'vue-extension.d.ts')
}

function write(data: any, filename: string) {
	const hybridlyPath = path.resolve(process.cwd(), '.hybridly')

	if (!fs.existsSync(hybridlyPath)) {
		fs.mkdirSync(hybridlyPath)
	}

	fs.writeFileSync(path.resolve(hybridlyPath, filename), data, {
		encoding: 'utf-8',
	})
}
